const DARK = {
  pageBg: 'bg-zinc-900',
  cardBg: 'bg-zinc-800',
  cardAltBg: 'bg-zinc-900',
  border: 'border-zinc-600',
  divider: 'border-zinc-600',
  rowBg: 'bg-zinc-800',
  rowActive: 'active:bg-zinc-700',
  sectionTitle: 'text-zinc-400',
  textPrimary: 'text-zinc-100',
  textSecondary: 'text-zinc-400',
  title: 'text-zinc-100',
  subtitle: 'text-zinc-100',
  subtext: 'text-zinc-400',
  iconBg: 'bg-zinc-700',
  iconColor: '#F8FAFC',
  icon: '#F8FAFC',
  chevron: '#A1A1AA',
  switchTrackOff: '#52525B',
  switchTrackOn: '#52525B',
  line: 'bg-zinc-700',
  emptyIcon: '#A1A1AA',
  albumEmptySecondary: 'text-zinc-500',
  avatarGradient: 'from-zinc-500 to-zinc-700',

  headerBg: 'bg-zinc-800',
  inputBg: 'bg-zinc-700',
  inputText: 'text-zinc-100',
  inputBorder: 'border-zinc-600',
  inputPlaceholder: '#A1A1AA',
  count: 'text-zinc-400',
  loading: '#F8FAFC',
  loadingText: 'text-zinc-400',

  headerText: 'text-zinc-100',
  pickerTitle: 'text-zinc-100',
  pickerSub: 'text-zinc-400',
  pickerCircle: 'bg-zinc-100',
  pickerCircleIcon: '#111111',
  clearBtn: 'bg-zinc-600',
  clearText: 'text-zinc-200',
  infoIcon: '#A1A1AA',
  infoText: 'text-zinc-400',

  secondaryBtn: 'bg-zinc-700',
  secondaryText: 'text-zinc-200',
  button: 'bg-zinc-100',
  buttonText: 'text-zinc-900',
  footer: 'text-zinc-400',

  menuBg: 'bg-zinc-800',
  menuBorder: 'border-zinc-600',
  rowBorder: 'border-zinc-700',
  text: 'text-zinc-100',
  fabBg: 'bg-zinc-100',
  fabIcon: '#111111',

  sheetBg: 'bg-zinc-800',
  sheetBorder: 'border-zinc-700',
  body: 'text-zinc-300',
  tagBg: 'bg-zinc-700',
  tagText: 'text-zinc-300',
  placeholderBg: 'bg-zinc-700',
};

const LIGHT = {
  pageBg: 'bg-gray-50',
  cardBg: 'bg-white',
  cardAltBg: 'bg-white',
  border: 'border-gray-100',
  divider: 'border-gray-100',
  rowBg: 'bg-white',
  rowActive: 'active:bg-gray-50',
  sectionTitle: 'text-gray-500',
  textPrimary: 'text-gray-900',
  textSecondary: 'text-gray-500',
  title: 'text-black',
  subtitle: 'text-black',
  subtext: 'text-gray-400',
  iconBg: 'bg-gray-100',
  iconColor: '#111111',
  icon: '#111111',
  chevron: '#9CA3AF',
  switchTrackOff: '#E5E7EB',
  switchTrackOn: '#52525B',
  line: 'bg-gray-200',
  emptyIcon: '#C8C8C8',
  albumEmptySecondary: 'text-gray-300',
  avatarGradient: 'from-zinc-500 to-zinc-700',

  headerBg: 'bg-white',
  inputBg: 'bg-gray-100',
  inputText: 'text-gray-900',
  inputBorder: 'border-gray-300',
  inputPlaceholder: '#6B7280',
  count: 'text-gray-400',
  loading: '#000000',
  loadingText: 'text-gray-500',

  headerText: 'text-black',
  pickerTitle: 'text-black',
  pickerSub: 'text-gray-500',
  pickerCircle: 'bg-[#121212]',
  pickerCircleIcon: 'white',
  clearBtn: 'bg-gray-200',
  clearText: 'text-gray-700',
  infoIcon: '#999999',
  infoText: 'text-gray-400',

  secondaryBtn: 'bg-gray-100',
  secondaryText: 'text-gray-700',
  button: 'bg-black',
  buttonText: 'text-white',
  footer: 'text-gray-500',

  menuBg: 'bg-white',
  menuBorder: 'border-gray-200',
  rowBorder: 'border-gray-100',
  text: 'text-black',
  fabBg: 'bg-[#121212]',
  fabIcon: 'white',

  sheetBg: 'bg-white',
  sheetBorder: 'border-gray-100',
  body: 'text-gray-600',
  tagBg: 'bg-gray-100',
  tagText: 'text-gray-600',
  placeholderBg: 'bg-gray-200',
};

export const getThemeColors = (isDarkMode) => {
  return isDarkMode ? DARK : LIGHT;
}
